[ConnectServerInfo]
ConnectServerPortTCP =44495
ConnectServerPortUDP =55562
Version = Premium
MaxIpConnection =10
;When set to 1, the process auto-detects the IP - no configuration needed, just run the server
IPType = 0
