[SuperKhung]
;----------------------------------------------------------------------------
CustomerName		= SuperKhung
ClientSerial		= K-838858iMu
ClientVersion 		= 1.03.34
;----------------------------------------------------------------------------
IpAddress 			= 127.0.0.1
IpAddressPort 		= 44495
WindowName 			= SEASON 6EP5 - [5.2]
ClientName 			= Engine.exe
ScreenShotPath		= Photos\Screen(%02d_%02d-%02d-%02d)-%04d.jpg
;----------------------------------------------------------------------------
;Max cửa sổ game
MaxGameInstances 	= 5
;Bật tắt chế độ tự động kết nối lại 0 tắt - 1 bật
ReconnectTime 		= 1
;Camera Mặc định cao nhất.
CameraDefault 		= 45
;;Hiệu ứng item dùng Plugin bên ngoài ( OK )
;PluginName 		= ScaleForm.dll
AntiPort 			= 55858
;----------------------------------------------------------------------------
;Sub Server

ServerName_1 = Europe
ServerName_2 = Europe
ServerName_3 = Europe
ServerName_4 = Europe
;----------------------------------------------------------------------------
;==================================================
; Tốc độ tối đa dựa trên điểm nhanh nhẹn (Agility) của nhân vật
;==================================================
DWMaxAttackSpeed = 65000
DKMaxAttackSpeed = 65000
FEMaxAttackSpeed = 65000
MGMaxAttackSpeed = 65000
DLMaxAttackSpeed = 65000
SUMaxAttackSpeed = 65000
RFMaxAttackSpeed = 65000
;----------------------------------------------------------------------------
;FPS mặc định 70
DefaultFPS = 240.0
;----------------------------------------------------------------------------
;Sử dụng Skill Mana của vũ khí khi mang Pet Cỡi [Bật 0/ 1 tắt
SkillManaPet = 1
;----------------------------------------------------------------------------
MENU_BUTTON_01 = 1    ; Ranking
MENU_BUTTON_02 = 1    ; Event Time
MENU_BUTTON_03 = 1    ; Relife
MENU_BUTTON_04 = 1    ; Reset Change
MENU_BUTTON_05 = 1    ; Danh Hieu
MENU_BUTTON_06 = 1    ; Spin
MENU_BUTTON_07 = 1    ; VIP / ID Level
MENU_BUTTON_08 = 1    ; Donate / Moc Nap
MENU_BUTTON_09 = 1    ; Change Class
MENU_BUTTON_10 = 1    ; Change Pass
MENU_BUTTON_11 = 1    ; Hon Hoan
MENU_BUTTON_12 = 1    ; X-Shop / New Shop
MENU_BUTTON_13 = 1    ; Cultivation / Tu Luyen
MENU_BUTTON_14 = 1    ; Military Rank / Quan Ham
MENU_BUTTON_15 = 1    ; Stars Option
MENU_BUTTON_16 = 1    ; Gems Shop

MENU_BUTTON_17 = 0    ; Chua dung
MENU_BUTTON_18 = 0    ; Chua dung
MENU_BUTTON_19 = 0    ; Chua dung
MENU_BUTTON_20 = 0    ; Chua dung

;----------------------------------------------------------------------------
;Bật tắt 3 Nút ở bảng C ( 0 tắt, 1 Bật )
ButtonCharracter 	= 1
;----------------------------------------------------------------------------
;Bảng thông tin Stats chỉ số ở bảng C. ( 0 tắt, 1 Bật )
TabInfoStats = 1
;Bật tắt nút Treo shop tiền tệ ( 0 tắt, 1 bật )
ButtonShopWcoinC 	= 1
ButtonShopWcoinP 	= 1
ButtonShopWcoinG 	= 1
ButtonShopJwBless 	= 1
ButtonShopJwSoul 	= 1
ButtonShopChaos 	= 1
ButtonShopZens 		= 1

;----------------------------------------------------------------------------
;Top Tổng
Ranking1 = 1
;Top Tài Phú
Ranking2 = 1
;Top Guid
Ranking3 = 1
;Top PK
Ranking4 = 1
;Top Sự Kiện
Ranking5 = 1
;Top Master
Ranking6 = 1
;Top Nhiệm Vụ
Ranking7 = 1
;----------------------------------------------------------------------------
MaxLevelDanhHieu  	= 20
MaxLevelQuanHam  	= 12
MaxLevelTuChan  	= 20
MaxLevelHonHoan  	= 50


; Bật tắt Coin trên tiêu đề game.
EnableCoinTitle = 0

;Bật tắt thông tin 3 dòng text trong game. 43, 44, 45 ( file TextHtml.txt )
TextTips3Line = 0

;Để cho class được phép mang trang bị khác. Cần sửa Item.txt trên server cho phép, sau đó biên dịch sang Item.bmd cho Client.
;Bật tắt Slot Găng Tay cho RF ở hòm đồ
RF_GLOVE = 0
;Bật tắt Slot Mũ cho Magic ở hòm đồ
MG_HELM = 0

;Bật tắt tạo nhân vật RF/SM [0 tạo đủ, 1, bỏ RF, 2, bỏ RF và SM] 
CreateCharSeason = 0

;Disable Button Class UP ( 0: ON, 1: OFF)
ButtonClassUP = 1
;Disable Jewelbank Tab: 0 = 3 tab; 1 = 2 tab; 2 = 1 tab
JewelBankTab = 2