;==============================================================
;========================= SUPERKHUNG =========================
;==============================================================
;Crc File Checked Main 5.2! Code by SuperKhung [0775.838.858]
;==============================================================
SPK_MEXE                            = 0xB187DC1B
SPK_PBMD                            = 0x7D56FCEB
SPK_SDBMD                           = 0xF49A31E5
;==============================================================
CustomPetEffect                     = FOUND OK!
CustomPetGlow                       = FOUND OK!
JCItemToolTip                       = FOUND OK!
JCTextTooltip                       = FOUND OK!
CustomClaws                         = FOUND OK!
CustomPet                           = FOUND OK!
CustomBowCross                      = FOUND OK!
CustomItem                          = FOUND OK!
CustomWing                          = FOUND OK!
;==============================================================
CustomMonster.bmd                   = FOUND OK!
RenderEffect.bmd                    = FOUND OK!
CustomIconBuff.bmd                  = FOUND OK!
CustomItemColorName.bmd             = FOUND OK!
CustomItemPosition.bmd              = FOUND OK!
CustomJewel.bmd                     = FOUND OK!
CustomModelNpc.bmd                  = FOUND OK!
CustomMonster.bmd                   = FOUND OK!
CustomMonsterGold.bmd               = FOUND OK!
CustomNpcName.bmd                   = FOUND OK!
CustomRingPen.bmd                   = FOUND OK!
CustomSetEffect.bmd                 = FOUND OK!
;==============================================================
; Wednesday, 14:23:56 19/08/2026
;==============================================================
