[ServerInfo]
;==========================
CustomerName 	=SuperKhung
ClientVersion 	=1.03.34
ClientSerial 	=K-838858iMu
AntihackPort 	=55858
;==========================
AntiFloodSwitch 	=1
ThoiGianKhoaIPDos 	=30

LauncherName =Launchers.exe
