[JoinServerInfo]
JoinServerODBC =SPK5.2
JoinServerPort =55975
ConnectServerAddress = 127.0.0.1
ConnectServerPort =55562
CaseSensitive = 0
MD5Encryption = 0
SPKGLPW =dCgEIa5iNt

;Enable/disable in-game registration
RegNewAccount 			=0
ChieuDaiKyTu 			=4
CharAccountReg			=0
